spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vollmed_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

# Si se quiere usar una BDD local como h2 se debe borra la anotacion
# @AutoConfigureTestDatabase en MedicoRepositoryTest

# spring.datasource.url = jdbc:h2:mem:testdb
# spring.datasource.driverClassName = org.h2.Driver
# spring.datasource.username = sa
# spring.datasource.password = root
# spring.jpa.database-platform = org.hibernate.dialect.H2Dialect